# Generated by Django 3.1.7 on 2021-04-01 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_xid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.UUIDField(blank=True, default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('EN', 'enabled'), ('DS', 'disabled')], default='EN', max_length=2)),
                ('balance', models.IntegerField(default=0)),
                ('enabled_at', models.DateTimeField()),
                ('disabled_at', models.DateTimeField(blank=True)),
                ('withdrawn_at', models.DateTimeField(blank=True)),
                ('deposited_at', models.DateTimeField(blank=True)),
                ('deposited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposited_by', to='wallet.userprofile')),
                ('owned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to='wallet.userprofile')),
                ('withdrawn_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawn_by', to='wallet.userprofile')),
            ],
        ),
    ]
