# Generated by Django 3.1.7 on 2021-04-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='deposited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
