# Generated by Django 3.1.7 on 2021-04-01 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20210401_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallets',
            name='deposited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposited_by', to='wallet.userprofile'),
        ),
        migrations.AlterField(
            model_name='wallets',
            name='withdrawn_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawn_by', to='wallet.userprofile'),
        ),
    ]
