# Generated by Django 3.1.7 on 2021-04-01 10:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_auto_20210401_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallets',
            name='deposited_at',
        ),
        migrations.RemoveField(
            model_name='wallets',
            name='deposited_by',
        ),
        migrations.RemoveField(
            model_name='wallets',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='wallets',
            name='withdrawn_at',
        ),
        migrations.RemoveField(
            model_name='wallets',
            name='withdrawn_by',
        ),
        migrations.CreateModel(
            name='withdrawals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawn_by', to='wallet.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Deposits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('deposited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposited_by', to='wallet.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='wallets',
            name='deposited_reference_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Deposits', to='wallet.deposits'),
        ),
        migrations.AddField(
            model_name='wallets',
            name='withdrawn_reference_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallet.withdrawals'),
        ),
    ]
