# Generated by Django 3.1.7 on 2021-04-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_auto_20210401_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposits',
            old_name='withdrawn_at',
            new_name='deposited_at',
        ),
    ]
